### ISSUE TITLE
Schema do DB

### ISSUE THREAD

**Issue by lagden** [TExTecnologia/webhook-teleport#3]
Abaixo esta é uma proposta de tabelas para o sistema de webhook:

```yaml
ContentType:
  indexes:
    tipo_index: { fields: [tipo] }
  columns:
    tipo: { type: string, notnull: true, unique: true }
    nome: { type: string, notnull: true }
  relations:
    Payloads:
      type: many
      class: ContentType
      local: tipo
      foreign: content_type

Evento:
  indexes:
    uuid_index: { fields: [uuid] }
    nome_index: { fields: [nome] }
  columns:
    uuid: { type: string(36), notnull: true, unique: true }
    nome: { type: string, notnull: true, unique: true }

# http://lornajane.net/posts/2016/mysql-5-7-json-features
Log:
  indexes:
    uuid_index: { fields: [uuid] }
  columns:
    uuid: { type: string(36), notnull: true, unique: true }
    request: { type: json }
    response: { type: json }

Payload:
  indexes:
    uuid_index: { fields: [uuid] }
    empresa_index: { fields: [empresa_id] }
  columns:
    uuid: { type: string(36), notnull: true, unique: true }
    url: { type: string }
    segredo: { type: string }
    content_type: { type: string(36) }
    empresa_id: {type: string(36), notnull: true}
  relations:
    ContentType:
      local: content_type
      foreign: tipo
      onDelete: CASCADE
    Evento:
      refClass: PayloadEvento
      alias: Eventos
      foreignAlias: Payloads
    Log:
      refClass: PayloadLog
      alias: Logs
      foreignAlias: Payloads

PayloadEvento:
  columns:
    payload_uuid: { type: string(36) }
    evento_uuid: { type: string(36) }
  relations:
    Payload: { local: payload_uuid, onDelete: CASCADE }
    Evento: { local: evento_uuid, onDelete: CASCADE }

PayloadLog:
  columns:
    payload_uuid: { type: string(36) }
    log_uuid: { type: string(36) }
  relations:
    Payload: { local: payload_uuid, onDelete: CASCADE }
    Log: { local: log_uuid, onDelete: CASCADE }
```
